name: previsao_do_tempo
description: A new Flutter project. Created by Slidy
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sqflite: ^1.3.1
  dio_http_cache: ^0.2.7
  hive: ^1.4.1+1
  shimmer: ^1.1.1
  intl: ^0.16.1
  get: ^3.2.2
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.2.7+1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/01d.png
    - assets/images/01n.png
    - assets/images/02d.png
    - assets/images/02n.png
    - assets/images/03d.png
    - assets/images/03n.png
    - assets/images/04d.png
    - assets/images/04n.png
    - assets/images/09d.png
    - assets/images/09n.png
    - assets/images/10d.png
    - assets/images/10n.png
    - assets/images/11d.png
    - assets/images/11n.png
    - assets/images/13d.png
    - assets/images/13n.png
    - assets/images/50d.png
    - assets/images/50n.png
    - assets/images/background.jpg

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
    mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs

  
